Adding mj-style and preparing version 1.7
mjmlio/language-mjml pull request #7
Opened 2016-10-06 09:38 UTC by arthurkatz

Following Atom 3.0.0 release

2016-10-06 12:22 UTC, ngarnier requested changes
Thanks @arthurkatz, providing updates even before the MJML version is released... you're amazing 🙌

2016-10-06 12:22 UTC, ngarnier commented on package.json
> +  "version": "1.7.0",
Please do not update the version in package.json, Atom does it automatically on publish

2016-10-06 12:24 UTC, arthurkatz commented
Oh I didn't knew, I'm fixing this ;)

Le jeudi 6 octobre 2016, Nicolas Garnier <notifications@github.com> a
écrit :

> *@ngarnier* requested changes on this pull request.
>
> Thanks @arthurkatz <https://github.com/arthurkatz>, providing updates
> even before the MJML version is released... you're amazing 🙌
> ------------------------------
>
> In package.json
> <https://github.com/mjmlio/language-mjml/pull/7#pullrequestreview-3099667>
> :
>
> > @@ -1,6 +1,6 @@
>  {
>    "name": "language-mjml",
> -  "version": "1.6.0",
> +  "version": "1.7.0",
>
> Please do not update the version in package.json, Atom does it
> automatically on publish
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mjmlio/language-mjml/pull/7#pullrequestreview-3099667>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEPi8-9JNeV2F-DJlJ5jzQhLYOHVBXfNks5qxOgBgaJpZM4KPvRB>
> .
>

2016-10-06 14:13 UTC, arthurkatz commented
@ngarnier fixed

2016-10-06 14:18 UTC, arthurkatz commented
Next step is to add CSS colors into mj-style's content

2016-10-18 13:11 UTC, ngarnier commented
hey @arthurkatz, thanks again. I just tested it as we're about to release MJML v3 but it seems there's an issue. When typing `style`+tab, the component unwrapped is <mj-chart />, as seen here: 

![](http://g.recordit.co/cQtgTeDg29.gif)

Anyway, we haven't merged `mj-chart` yet so it'd be better if you can just remove it for now.

2016-10-19 23:43 UTC, arthurkatz commented
Fixed !

2016-10-20 08:20 UTC, ngarnier commented
Looking good, merging 🚀 ! Thanks Arthur

2016-10-20 08:20 UTC, merged